services:
  - name: my-backend
    type: web_service
    env: python
    region: oregon
    branch: main
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app

  - name: my-frontend
    type: web_service
    env: static
    region: oregon
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: build
