# render.yaml
services:
  - type: web
    name: url-grabber-app
    env: python
    rootDir: .
    buildCommand: |
      echo "--- Starting Frontend Build Process ---"
      echo "Current directory before cd client: $(pwd)"
      ls -la # List contents of the root directory

      echo "Changing directory to client/"
      cd client
      echo "Current directory after cd client: $(pwd)"
      ls -la # List contents of the client directory

      echo "Running npm install in client/"
      npm install
      if [ $? -ne 0 ]; then
        echo "ERROR: npm install failed in client/."
        exit 1
      fi
      echo "npm install completed successfully."
      ls -la node_modules # Verify node_modules exists and has content

      echo "Running npm run build in client/"
      npm run build
      if [ $? -ne 0 ]; then
        echo "ERROR: npm run build failed in client/."
        exit 1
      fi
      echo "npm run build completed successfully."
      ls -la build # Verify build folder exists
      ls -la build/index.html # Verify index.html exists inside build

      echo "Changing directory back to root (cd ..)"
      cd ..
      echo "Current directory after cd ..: $(pwd)"
      ls -la # List contents of the root directory again

      echo "--- Starting Backend Install Process ---"
      echo "Running pip install -r requirements.txt"
      pip install -r requirements.txt
      if [ $? -ne 0 ]; then
        echo "ERROR: pip install failed."
        exit 1
      fi
      echo "pip install completed successfully."
      echo "--- Build Process Complete ---"
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
    plan: free
