services:
  - type: web
    name: downloader-app-react
    env: python
    plan: free
    buildCommand: |
      cd client && npm install && npm run build
      cd ../server && pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
