services:
  - type: web
    name: downloader-app-react
    runtime: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    buildCommand: "cd client && npm install && npm run build && cd ../server && pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
